trigger: none

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfdestroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall version 1.1.5
            inputs:
              terraformVersion: '1.1.5'
          - task: DownloadSecureFile@1
            displayName: download secure files
            inputs:
              secureFile: 'terraform-azure.pem.pub'
              retryCount: '2'
          - task: DownloadSecureFile@1
            inputs:
              secureFile: 'terraform.tfvars'
              retryCount: '2'
          - task: CmdLine@2
            displayName: create ssh-keys dir
            inputs:
              script: 'mkdir ssh-keys'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              failOnStderr: true
          - task: CopyFiles@2
            displayName: 'move secure files to ssh-keys'
            inputs:
              SourceFolder: $(Agent.TempDirectory)
              Contents: 'terraform-azure.pem.pub'
              TargetFolder: $(System.DefaultWorkingDirectory)/ssh-keys
          - task: CopyFiles@2
            displayName: 'move terraform.tfvars to repo root'
            inputs:
              SourceFolder: $(Agent.TempDirectory)
              Contents: 'terraform.tfvars'
              TargetFolder: $(System.DefaultWorkingDirectory)
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'bobbing-for-apples-sp'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'bobbing-for-apples-sp'